// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbzhevdcvgvldvrbuzaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiemhldmRjdmd2bGR2cmJ1emF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MzQ4MTQsImV4cCI6MjA1OTMxMDgxNH0.bM3Gj8-MG75tcn14tE422DgJIu4ttknTyT9ro_-aliE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);